### ISSUE TITLE
The Geometric  parser is not working correctly 

### ISSUE THREAD

**Issue by AghaKhan** [ratishphilip/CompositionProToolkit#11]
To see this problem please create this svg file
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"  viewBox="0 0 500 500">
<defs>
	<radialGradient id="ExampleGradient" cx="119.74" cy="818.65" r="473.95" gradientTransform="translate(69.73 -646.3)" gradientUnits="userSpaceOnUse">
      <stop offset="0.09" stop-color="#8e989c"/>
      <stop offset="0.39" stop-color="#6a7275"/>
      <stop offset="0.91" stop-color="#050505"/>
    </radialGradient>
</defs>
<path fill="url(#ExampleGradient)" d="M69.73,147.4H468.85a50,50,0,0,1,49.89,49.89V596.41a50,50,0,0,1-49.89,49.89H69.73a50,50,0,0,1-49.89-49.89V197.29A50,50,0,0,1,69.73,147.4Z" transform="translate(-19.84 -147.4)"/>
</svg>

Now create an application with Win2D and create same path. The image you get is not the same.
You write beautiful code (I can't write code like you do) and started to look your code and parsed my path and realized there is bug in your code. In this example you placed first 2 element and then third element is wrong.  I experimented with many complex svg files and saw the output image is not correct. 
Thank you for sharing code with me. Good luck
best regards
aghaDotKhanAtHotmailDotCom

**Comment by AghaKhan** [comment]
[example.pdf](https://github.com/ratishphilip/CompositionProToolkit/files/1202583/example.pdf)

**Comment by ratishphilip** [comment]
Thanks for reporting this. Let me have a look.

**Comment by AghaKhan** [comment]
Thank you my friend Ratish Philip:
Thank you for sharing code with me.

https://1drv.ms/f/s!AtjIdnVOoJXtluRlhqxfQT3_QUPxrg


When you have time please download my applications.
Please look at TimeMachine.
ThemeClock and double click on it.

Rubik’s cube.

Similar work I would like to do under Win2D.

Best regards
Agha Khan



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ratishphilip** [comment]
@AghaKhan I had a look at the svg defined in example.pdf file.

It seems that there is an extra line break in the path data which is causing the issue. (after **1-**, see image below)
![svg_error](https://user-images.githubusercontent.com/7021835/31047168-63071ec4-a5ba-11e7-91cb-cb848848a0d8.png)

**Comment by ratishphilip** [comment]
Closing this as the problem was with the svg data.
