### ISSUE TITLE
appreciation post

### ISSUE THREAD

**Issue by touseefbsb** [ratishphilip/CompositionProToolkit#17]
this is just an appreciation post here, brilliant controls and so much powerful composition controls. I was just wondering will you keep adding more features and controls to this library? bcz it seems u really know ur stuff around composition library and I hope u keep maintaining it, if you need any suggestions about new controls ill be happy to suggest some.

**Comment by ratishphilip** [comment]
Hi @touseefbsb,
Thank you so much for your appreciation.
I do intend to keep maintaining this library and adding new features & controls.

Your suggestions are welcome.

**Comment by touseefbsb** [comment]
first of all I wanted to discuss with you about the Windows Dev Ui Samples Gallery. I am sure you know about that repo, maintained by Microsoft for composition stuff for uwp apps.the problem I found with that app is even a simple control/feature for example **shyHeader** is very complicated to implement, there is a lot of c# code behind and xaml stuff goes on, which is very specific to exact scenario they provide there, I do understand composition stuff takes a lot of **Disposing** to do, and also for many scenarios lot of code has to be written. but with fluent design coming in and Visual Layer apis becoming simpler and simpler, I think now it should be relatively easier to implement such scenarios, blur background used to be a big deal now its just a like a background color for anything and part of uwp community toolkit, every feature of Windows dev ui samples, wherever they include an image they use **compositionImage** which is a custom control which can be used in all scenarios, but whenever I try to replicate their functionality in my apps it gets very complicated, lots of moving parts and I always end up with some errors and never been able to replicte anything in my app. I wish like u have maintained this library and built proper controls which are straight forward xaml controls, this is how it should be done. and if there is any risks related to disposing and stuff, u can just provide it in documentation like u already did , which is perfect. Whats ur take on all of this ? @ratishphilip

**Comment by touseefbsb** [comment]
also the new preview sdk ( just released ) https://blogs.windows.com/buildingapps/2018/03/30/windows-10-sdk-preview-build-17125/
has a lot of new composition apis , maybe you wanna have a look :)

**Comment by ratishphilip** [comment]
Closing.
