### ISSUE TITLE
Virtualization or Incemental Loading for FluidWrapPanel

### ISSUE THREAD

**Issue by ivanvs** [ratishphilip/CompositionProToolkit#18]
Hi,

Firstly, I would like to thank you for such a great controls. 

Secondly, could you tell me if you plan to add virtualization or incremental loading to FluidWrapPanel? If this is not in your plan, could you give me suggestion how that can be added?

**Comment by ratishphilip** [comment]
Hi @ivanvs,

Sorry for the late reply. 
First of all FluidWrapPanel derives from Panel and not from ItemsControl. 
You need to create a control which derives from ItemsControl and implement virtualization in that control and then use the FluidWrapPanel as your ItemsPanel.

**Comment by ivanvs** [comment]
Hi @ratishphilip ,

Thank you for your answer. Sadly, I am not working on that project any more, but I am sure that this will help somebody with similar issue.
