### ISSUE TITLE
Conflict with UWP Community Toolkit

### ISSUE THREAD

**Issue by seanocali** [ratishphilip/CompositionProToolkit#19]
Please see [this](https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/2629).

**Comment by ratishphilip** [comment]
Thanks, I will look into it.

**Comment by ratishphilip** [comment]
@seanocali At the first look it seems like you are using **Windows SDK v17134** and CompositionProToolkit **v0.9** (which requires **Windows SDK v17723**) and it might be the issue.

Could you use CompositionProToolkit **v0.8** (which is based on **Windows SDK v17134**) and see if the issue still persists?

**Comment by seanocali** [comment]
I tried v0.8 and the issue did not occur so you are correct, thanks. I would try v0.9 with 17723 but I am no longer an insider.

**Comment by ratishphilip** [comment]
Closing this issue as it is resolved by using v0.8 of CompositionProToolkit.

**Comment by seanocali** [comment]
Just an FYI, I joined insider again, installed 1809, and tried v0.9 and it worked.
