### ISSUE TITLE
GetHashedFileNameAsync/ImageCache error checking

### ISSUE THREAD

**Issue by mediabuff** [ratishphilip/CompositionProToolkit#20]
It would help to  check for failure of this when objectToHash to not supported type. Right now the program crashed with no explanation. I had to get the source code version to debug. The program faults with argument null exception.

**Comment by ratishphilip** [comment]
thanks for reporting it. 
Let me have a look at it.

**Comment by ratishphilip** [comment]
ImageFrame in V1.0 no longer uses ImageCache. Providing the Uri should load the image correctly.
