### ISSUE TITLE
GetCachedUriAsync for 'file' schema

### ISSUE THREAD

**Issue by mediabuff** [ratishphilip/CompositionProToolkit#21]
my images are in network file share with Uri such as 'file://....'. So, caching does'nt work for this. what is the solution. And the images don't get displayed.

**Comment by ratishphilip** [comment]
Let me have a look at it.

**Comment by ratishphilip** [comment]
ImageFrame in V1.0 no longer uses ImageCache. Providing the Uri should load the image correctly.
