### ISSUE TITLE
raising devicelost when the device is not lost

### ISSUE THREAD

**Issue by ashfaquddin** [ratishphilip/CompositionProToolkit#9]
This API was unexpectedly called when the Direct3D device is not lost.
   at Microsoft.Graphics.Canvas.CanvasDevice.RaiseDeviceLost()
   at CompositionProToolkit.CompositionGenerator.OnDisplayContentsInvalidated(DisplayInformation sender, Object args)

**Comment by ratishphilip** [comment]
@ashfaq-uddin 
Can you please provide more details of your scenario where this happened?

**Comment by ashfaquddin** [comment]
on a multimonitor setup switch off one monitor and you will get this

**Comment by ratishphilip** [comment]
@ashfaq-uddin with the release of **v0.6**, **CompositionProToolkit** now uses the **DeviceLostHelper**.

Could you please check whether this issue is still happening?

**Comment by ratishphilip** [comment]
This issue has been fixed in v0.6.
